# ci/cd practice file 
name: cicd pipeline

on:
  push:
    branches:
      - main

jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name: pull code from github
          run: echo "git pull"
    
    build:
      runs-on: ubuntu-latest
      steps:
        - name: docker build
          run: echo "docker build -t app-name ."

    test:
      runs-on: ubuntu-latest
      steps:
        - name: test the code
          run: echo "test application code"
          
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: deploy on server
          run: echo "Deploy application on AWS"
