# ci/cd practice file 
name: cicd pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Applications
        run: npm run build
      
