name: Nodejs Workflow
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where the workflow runs
        default: "main"
        required: true
        type: choice
        options:
          - main
          - prod
          - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 24
            - name: Install Dependencies
              run: npm install

            - name: Run tests
              run: npm test